---

- name: Add Atom GPG key.
  rpm_key:
    key: https://packagecloud.io/AtomEditor/atom/gpgkey
    state: present

- name: Add Atom repository.
  yum_repository:
    name: Atom
    baseurl: https://packagecloud.io/AtomEditor/atom/el/$releasever/$basearch
    description: Atom Editor
    enabled: yes
    file: atom.repo
    gpgcheck: no
    gpgkey: https://packagecloud.io/AtomEditor/atom/gpgkey
    repo_gpgcheck: no
